name: Build Docker Image and Push to ghcr.io

# 当 push 到 main 分支，或者创建以 v 开头的 tag 时触发，可根据需求修改
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # 这里用于定义 GITHUB_TOKEN 的权限
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: auto-website
          registry: ghcr.io
          githubOrg: override-org # optional
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
